// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7NAv_2Pq-M328q5EBbNm6jXZML-FWZFE',
    appId: '1:514145139188:web:812673cdbf1b6ca1f7a1a1',
    messagingSenderId: '514145139188',
    projectId: 'flutter-chatapp-71e4d',
    authDomain: 'flutter-chatapp-71e4d.firebaseapp.com',
    storageBucket: 'flutter-chatapp-71e4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkg0NbkTqGgwjLFQAb4mfg4JO0I438LM',
    appId: '1:514145139188:android:25705d634ea1715af7a1a1',
    messagingSenderId: '514145139188',
    projectId: 'flutter-chatapp-71e4d',
    storageBucket: 'flutter-chatapp-71e4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGO_I8Mr3OQ71c0G8iLdVSxU1sT1gSjw',
    appId: '1:514145139188:ios:1b447b5aecd9dd36f7a1a1',
    messagingSenderId: '514145139188',
    projectId: 'flutter-chatapp-71e4d',
    storageBucket: 'flutter-chatapp-71e4d.appspot.com',
    iosClientId: '514145139188-bojft0mjvjk4c6d50rqm4n5kf91vdk7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGO_I8Mr3OQ71c0G8iLdVSxU1sT1gSjw',
    appId: '1:514145139188:ios:1b447b5aecd9dd36f7a1a1',
    messagingSenderId: '514145139188',
    projectId: 'flutter-chatapp-71e4d',
    storageBucket: 'flutter-chatapp-71e4d.appspot.com',
    iosClientId: '514145139188-bojft0mjvjk4c6d50rqm4n5kf91vdk7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
